// Code generated by Slice Machine. DO NOT EDIT.

import CounterCallout from './CounterCallout';
import Hero from './Hero';
import LogosCalllout from './LogosCalllout';
import ScrollZoomImages from './ScrollZoomImages';

export {
	CounterCallout,
	Hero,
	LogosCalllout,
	ScrollZoomImages,
};

export const components = {
	counter_callout: CounterCallout,
	hero: Hero,
	icon_line_thing: LogosCalllout,
	scroll_zoom_images: ScrollZoomImages,
};
