import { SliceZone } from '@prismicio/react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { createClient } from '../prismicio';
import { components } from '../slices/';

export default function Home({ page }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <SliceZone slices={page.data.slices} components={components} />
      </main>
    </div>
  );
}

export async function getStaticProps({ locale, previewData }) {
  const client = createClient({ previewData });
  const page = await client.getByUID('page', 'home', { lang: locale });

  return {
    props: {
      page,
    },
  };
}
