import Head from 'next/head';
import LogosCallout from '../components/LogosCallout';
import Navbar from '../components/Navbar';
import CounterCallout from '../components/CounterCallout';
import Hero from '../components/Hero';
import ScrollZoomSnippet from '../components/ScrollZoomImages';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <ScrollZoomSnippet />

        <CounterCallout />
        <LogosCallout />
      </main>
    </div>
  );
}
